# Generated by Django 4.1.2 on 2023-01-17 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('vat_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price_net', models.IntegerField()),
                ('price_gross', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('sku', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.CharField(choices=[('standard', 'standard'), ('international', 'international'), ('express', 'express')], max_length=20)),
                ('order_tax_type', models.CharField(choices=[('19%', '19%'), ('IGL', 'IGL'), ('Drittland', 'Drittland')], max_length=20)),
                ('payment', models.CharField(choices=[('Überweisung', 'Überweisung'), ('PayPal', 'PayPal'), ('eBay Managed Payments', 'eBay Managed Payments')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('WIP', 'WIP'), ('shipped', 'shipped'), ('return', 'return')], max_length=40)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('shipping_status', models.CharField(default='Pending', max_length=30)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.products')),
            ],
        ),
    ]
