# Generated by Django 4.1.2 on 2023-01-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='store.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='store.customers'),
        ),
    ]
