# Generated by Django 4.1.2 on 2023-01-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customers_phone_alter_customers_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
