# Generated by Django 4.1.2 on 2023-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customers_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(default='RET62536', max_length=50, null=True),
        ),
    ]
