# Generated by Django 4.1.2 on 2023-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customers_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(blank=True, default='RET62536', max_length=50, null=True),
        ),
    ]
