# Generated by Django 4.1.2 on 2023-01-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customers_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateField(max_length=20),
        ),
    ]
