# Generated by Django 4.1.2 on 2023-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orders_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='store.products'),
        ),
        migrations.DeleteModel(
            name='Order_Item',
        ),
    ]
