# Generated by Django 4.1.2 on 2023-01-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orders_products_delete_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
