# Generated by Django 4.1.2 on 2023-02-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='alabama', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_city',
            field=models.CharField(default='alabama', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_company_name',
            field=models.CharField(default='Google', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_country',
            field=models.CharField(default='Uganda', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_last_name',
            field=models.CharField(default='doe', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_street',
            field=models.CharField(default='street 4', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_street_2',
            field=models.CharField(default='street 4', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_sur_name',
            field=models.CharField(default='John', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_zip_code',
            field=models.CharField(default=23456, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='street_2',
            field=models.CharField(default='Street 4', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default=4567, max_length=50),
            preserve_default=False,
        ),
    ]
