# Generated by Django 4.1.2 on 2023-02-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_supplier_alter_order_customer_timeline_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notes', to='store.note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='timelines', to='store.timeline'),
        ),
    ]
