# Generated by Django 4.1.2 on 2023-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_note_alter_order_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(null=True, related_name='products', to='store.supplier'),
        ),
    ]
