# Generated by Django 4.1.2 on 2023-02-11 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_remove_order_note_remove_order_timeline_note_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='customer',
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
