# Generated by Django 4.1.2 on 2023-02-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_note_customer_remove_timeline_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField()),
                ('buying_price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sku',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='hell', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='allegro_name',
            field=models.CharField(default='iedj', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_detail',
            field=models.CharField(default='ijfniejd', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(default='ueihdiej', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.IntegerField(default='082730827'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(null=True, related_name='products', to='store.supplierproduct'),
        ),
    ]
