# Generated by Django 4.1.2 on 2023-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_supplierproduct_remove_supplier_buying_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
