# Generated by Django 4.1.2 on 2023-02-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_gross',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_net',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
